[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv venv",
  ". venv/bin/activate",
  "pip install python-telegram-bot==20.8 numpy aiohttp websockets requests pycryptodome pytz"
]

[start]
cmd = ". venv/bin/activate && python bot.py"
